
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db-master
      - db-slave-one
      - db-slave-two
    env_file:
      - .env

    networks:
      - backend

  db-master:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  db-slave-one:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "15432:15432"
    volumes:
      - postgres_data_slave_one:/var/lib/postgresql/data
    networks:
      - backend

  db-slave-two:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "25432:25432"
    volumes:
      - postgres_data_slave_two:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:
  postgres_data_slave_one:
  postgres_data_slave_two:

networks:
  backend:
    name: backend
